# Generated by Django 4.1.7 on 2023-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
